/*
 * This source file was generated by the Gradle 'init' task
 */
package tokio;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAMainMethod() {
        try {
            App.main(new String[]{});
        } catch (Exception e) {
            fail("Main method should not throw an exception");
        }
    }
}
